### ISSUE TITLE
Rules

### ISSUE THREAD

**Issue by msaktype** [morishitter/csscs#1]
# Rules
#### requireSpaceBeforeCombinator

valid

``` css
.foo + .bar {

}
```

invalid

``` css
.foo+ .bar {

}
```
#### requireSpaceAfterCombinator

valid

``` css
.foo + .bar {

}
```

invalid

``` css
.foo +.bar {

}
```
#### requireSpaceBetweenSelectorsAndDeclarationStartBlock

valid

``` css
.foo {

}
```

invalid

``` css
.foo{

}
```
#### disallowMultiSpacesBetweenSelectorsAndDeclarationStartBlock

valid

``` css
.foo {

}
```

invalid

``` css
.foo    {

}
```
#### disallowNewLineBetweenSelectorsAndDeclarationStartBlock

valid

``` css
.foo {

}
```

invalid

``` css
.foo
{

}
```
#### disallowSpacesBeforeStartSelector

valid

``` css
.foo {

}
```

invalid

``` css
  .foo {

}
```
#### requireSemicolonInLastDeclaration

valid

``` css
.foo {
  color: red;
}
```

invalid

``` css
.foo {
  color: red
}
```
#### requireNewLineAfterDeclarations

valid

``` css
.foo {
  color: red;
  padding: 10px;
}
```

invalid

``` css
.foo {
  color: red;padding: 10px;
}
```
#### requireNewLineAfterStartDeclarationBlock

valid

``` css
.foo {
  color: red;
}
```

invalid

``` css
.foo { color: red;padding: 10px;
}
```
#### requireNewLineBeforEndDeclarationBlock

valid

``` css
.foo {
  color: red;
}
```

invalid

``` css
.foo {
  color: red;padding: 10px; }
```
#### disallowSpacesBetweenPropertyAndColon

valid

``` css
.foo {
  color: red;
}
```

invalid

``` css
.foo {
  color : red;
}
```
#### requireIndentationBeforeProperty

valid

``` css
.foo {
  color: red;
}
```

invalid

``` css
.foo {
color: red;
}
```
